# Generated by Django 2.0.6 on 2019-03-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0002_auto_20190302_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='family',
            name='ID',
        ),
    ]
