# Generated by Django 2.0.6 on 2019-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0003_auto_20190302_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='familyName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
