# Generated by Django 2.0.6 on 2019-03-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='familyName',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
