# Generated by Django 2.0.6 on 2019-03-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0006_auto_20190302_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.BooleanField()),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('familyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='appeasemeal_app.Family')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
