# Generated by Django 2.0.6 on 2019-03-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FamilyMembers',
        ),
    ]
