# Generated by Django 2.0.6 on 2019-03-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0020_auto_20190302_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='familyName',
            field=models.CharField(max_length=20),
        ),
    ]
