# Generated by Django 2.0.6 on 2019-03-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0025_auto_20190303_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='Admin',
            field=models.CharField(max_length=3),
        ),
    ]
