# Generated by Django 2.0.6 on 2019-03-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0028_auto_20190303_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='Admin',
            field=models.NullBooleanField(),
        ),
    ]
