# Generated by Django 2.0.6 on 2019-03-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeasemeal_app', '0029_auto_20190303_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='Admin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='familyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyMembers', to='appeasemeal_app.Family'),
        ),
    ]
