# Generated by Django 2.0.6 on 2018-12-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
