# Generated by Django 2.0.6 on 2018-11-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0002_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='days',
            new_name='new_days',
        ),
    ]
