# Generated by Django 2.0.6 on 2018-12-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0003_customrecipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrecipes',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('pk',)},
        ),
    ]
