# Generated by Django 2.0.6 on 2018-11-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0003_auto_20181125_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_days',
            old_name='name',
            new_name='title',
        ),
    ]
