# Generated by Django 2.0.6 on 2018-11-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0004_auto_20181125_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_days',
        ),
    ]
