# Generated by Django 2.0.6 on 2018-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
