# Generated by Django 2.0.6 on 2018-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
