# Generated by Django 2.0.6 on 2018-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0008_calendarmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentDate', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='CalendarModel',
        ),
        migrations.DeleteModel(
            name='DaysOfTheWeek',
        ),
    ]
