# Generated by Django 2.0.6 on 2018-12-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0009_auto_20181201_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentdate',
            old_name='CurrentDate',
            new_name='today',
        ),
    ]
