# Generated by Django 2.0.6 on 2018-12-01 20:33

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0010_auto_20181201_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdate',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.today, verbose_name=datetime.date),
            preserve_default=False,
        ),
    ]
