# Generated by Django 2.0.6 on 2018-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0013_auto_20181201_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
