# Generated by Django 2.0.6 on 2018-12-01 23:45

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0014_auto_20181201_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default=django.utils.datetime_safe.datetime.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
